import Head from 'next/head'

const Layout = () => {
    
  const theme = "custom"; // basic || custom

  return (
    <>
     <Head>
        <title>Create Next App Here</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href={`/assets/themes/${theme}/general.css`} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={'wrapper'}>
        <div>You are in {theme} theme</div>
        <div className={'left-content'} onClick={() => alert("Click on left")}>
          <span>Left Content (Click me)</span>
        </div>
        <div className={'right-content'}>Right Content</div>
      </div>
      <ul>
        <li>Chỉnh sửa hình dạng, màu sắc div bằng css</li>
        <li>Chỉnh sửa vị trí div bằng css</li>
        <li>Chỉnh sửa text div bằng css</li>
        <li>Action, side effect sẽ được xử lí trong component</li>
        <li>
          Thêm mới theme bằng cách add một thư mục chứa các file css được quy
          định sẵn vào assets/theme
        </li>
      </ul>
    </>
  );
};

export default Layout;
